"""init

Revision ID: 26782fa3a778
Revises: 
Create Date: 2026-10-09 08:01:12.942031
"""
from alembic import op
import sqlalchemy as sa


revision = '26782fa3a778'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learners',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('grade_level', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('learner_id', sa.String(length=16), nullable=False),
    sa.Column('request', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('llm_provider', sa.String(length=16), nullable=True),
    sa.Column('llm_model', sa.String(length=60), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_learner_id'), 'agent_runs', ['learner_id'], unique=False)
    op.create_table('learner_patterns',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('learner_id', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('skill', sa.String(length=60), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('evidence_strength', sa.String(length=10), nullable=False),
    sa.Column('n_observations', sa.Integer(), nullable=False),
    sa.Column('n_terms', sa.Integer(), nullable=False),
    sa.Column('n_sources', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learner_patterns_learner_id'), 'learner_patterns', ['learner_id'], unique=False)
    op.create_table('records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.String(length=16), nullable=False),
    sa.Column('term', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=40), nullable=False),
    sa.Column('skill', sa.String(length=60), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('recorded_on', sa.Date(), nullable=True),
    sa.Column('submitted_late', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_learner_id'), 'records', ['learner_id'], unique=False)
    op.create_index(op.f('ix_records_term'), 'records', ['term'], unique=False)
    op.create_table('teacher_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.String(length=16), nullable=False),
    sa.Column('term', sa.String(length=8), nullable=False),
    sa.Column('teacher_id', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=40), nullable=True),
    sa.Column('skill', sa.String(length=60), nullable=True),
    sa.Column('sentiment', sa.String(length=12), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('recorded_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_observations_learner_id'), 'teacher_observations', ['learner_id'], unique=False)
    op.create_index(op.f('ix_teacher_observations_term'), 'teacher_observations', ['term'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern_id', sa.String(length=24), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('observation_id', sa.Integer(), nullable=True),
    sa.Column('document_ref', sa.String(length=300), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['observation_id'], ['teacher_observations.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['learner_patterns.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_pattern_id'), 'evidence', ['pattern_id'], unique=False)
    op.create_table('profile_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.String(length=16), nullable=False),
    sa.Column('pattern_id', sa.String(length=24), nullable=False),
    sa.Column('approval_id', sa.String(length=24), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['learner_patterns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_changes_learner_id'), 'profile_changes', ['learner_id'], unique=False)
    op.create_table('teacher_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern_id', sa.String(length=24), nullable=False),
    sa.Column('learner_id', sa.String(length=16), nullable=False),
    sa.Column('run_id', sa.String(length=24), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['learner_patterns.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_reviews_pattern_id'), 'teacher_reviews', ['pattern_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=24), nullable=True),
    sa.Column('tool_name', sa.String(length=60), nullable=False),
    sa.Column('tool_input', sa.JSON(), nullable=False),
    sa.Column('tool_output', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('agent_state', sa.String(length=32), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_run_id'), 'tool_calls', ['run_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['teacher_reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approvals')
    op.drop_index(op.f('ix_tool_calls_run_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_teacher_reviews_pattern_id'), table_name='teacher_reviews')
    op.drop_table('teacher_reviews')
    op.drop_index(op.f('ix_profile_changes_learner_id'), table_name='profile_changes')
    op.drop_table('profile_changes')
    op.drop_index(op.f('ix_evidence_pattern_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_teacher_observations_term'), table_name='teacher_observations')
    op.drop_index(op.f('ix_teacher_observations_learner_id'), table_name='teacher_observations')
    op.drop_table('teacher_observations')
    op.drop_index(op.f('ix_records_term'), table_name='records')
    op.drop_index(op.f('ix_records_learner_id'), table_name='records')
    op.drop_table('records')
    op.drop_index(op.f('ix_learner_patterns_learner_id'), table_name='learner_patterns')
    op.drop_table('learner_patterns')
    op.drop_index(op.f('ix_agent_runs_learner_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_table('learners')
    # ### end Alembic commands ###
